version: "3.8"

networks:
  trainee_network:
    driver: bridge

services:
  flask:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'flask run -h 0.0.0.0 -p "8000"'
    volumes:
      - .:/usr/src/flask_app/
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - trainee_network

  db:
    image: postgres:12.8
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: "${DATABASE_USER}"
        POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
        POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - 5432:5432
    networks:
      - trainee_network

volumes:
  postgres_data: